# An example element with some *very strange* properties

name = "test_element"
color = ["#FF00FF", "#00FF00"]
state = "solid"
behaviour = [["XX","XX","XX"],["XX","XX","XX"],["XX","XX","XX"]]
category = "solids"
tempHigh = 100
stateHigh = "gold"
density = 100
conduct = 1.0

[reactions]
water = {elem = "ash", elem2 = "pop", tempMin = -50, chance = 0.1}
cement = {elem1 = "sand", tempMin = 50}
blood = {elem1 = "n_explosion", chance = 0.05}